<a href="https://colab.research.google.com/github/Ankipatel8990/LetsUpgrade-AI-ML/blob/master/Day7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
d1=[[1,2,3,4],[5,6,7,8]]

In [3]:
a1=np.array(d1)

In [4]:
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


Lets check dimention of array

In [5]:
a1.ndim

2

In [6]:
a1.shape

(2, 4)

here 2 rowS AND 4 Columns

In [7]:
a1.dtype

dtype('int64')

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a[5]

5

In [18]:
a[5:8]

array([5, 6, 7])

In [20]:
a[5:8]=11
a

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a2=np.arange(15).reshape(3,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
a2[0]

array([0, 1, 2, 3, 4])

In [24]:
a2[:,0]

array([ 0,  5, 10])

In [25]:
a2[:,1]

array([ 1,  6, 11])

In [27]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a3[2]

array([7, 8, 9])

In [30]:
a3[0,2]

3

In [31]:
a3[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a3[2:]

array([[7, 8, 9]])

In [33]:
a3[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
a3[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [35]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
a4=np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a5=np.sqrt(a4)
a5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
a6=np.square(a5)
a6

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.sign(a5)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.exp(a5)

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692])

In [45]:
np.log(a5)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.34657359, 0.54930614, 0.69314718,
       0.80471896, 0.89587973, 0.97295507, 1.03972077, 1.09861229])

In [46]:
np.floor(a5)

array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3.])

In [47]:
np.ceil(a5)

array([0., 1., 2., 2., 2., 3., 3., 3., 3., 3.])

In [48]:
a=[1,2,3]
b=[4,5,6]
np.add(a,b)

array([5, 7, 9])

In [50]:
np.subtract(a,b)

array([-3, -3, -3])

In [51]:
np.multiply(a,b)

array([ 4, 10, 18])

In [52]:
np.fmax(a,b)

array([4, 5, 6])

In [53]:
np.mod(a,b)

array([1, 2, 3])

In [54]:
np.greater(a,b)

array([False, False, False])

In [55]:
np.greater(b,a)

array([ True,  True,  True])

In [56]:
np.greater_equal(a,b)

array([False, False, False])

In [57]:
np.equal(a,b)

array([False, False, False])

In [59]:

arrsts=np.array([[0,1,2],[3,4,5],[6,7,8]])
arrsts

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:

arrsts.mean()

4.0

In [61]:
arrsts.std()

2.581988897471611

In [62]:
arrsts.var()

6.666666666666667

In [66]:
a7=np.array([[1,2,3],[2,3,4]])
a7

array([[1, 2, 3],
       [2, 3, 4]])

In [68]:
z=np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:

np.append(a7,z,axis=0)

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:

np.append(a7,z,axis=1)

array([[1., 2., 3., 0., 0., 0.],
       [2., 3., 4., 0., 0., 0.]])